"""Framework-independent unit-test generation records."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import StrEnum
from uuid import UUID

from codepilot_api.domain.explanations.entities import RepositoryFunction


class UnitTestFramework(StrEnum):
    """Unit-test frameworks emitted by CodePilot."""

    PYTEST = "pytest"
    JEST = "jest"
    JUNIT = "junit"


class TestCoverageKind(StrEnum):
    """Required scenario categories in every generated unit-test file."""

    HAPPY_PATH = "happy_path"
    EDGE_CASES = "edge_cases"
    INVALID_INPUTS = "invalid_inputs"
    BOUNDARY_TESTS = "boundary_tests"


@dataclass(frozen=True, slots=True)
class TestGenerationContext:
    """Bounded source evidence submitted to one test-generation provider."""

    repository_id: UUID
    repository_version_id: UUID
    function: RepositoryFunction
    end_line: int
    framework: UnitTestFramework
    test_file_path: str
    source: str


@dataclass(frozen=True, slots=True)
class GeneratedTestPayload:
    """A schema-validated unit-test artifact generated by an AI provider."""

    model: str
    summary: str
    test_code: str
    coverage: tuple[TestCoverageKind, ...]
    notes: tuple[str, ...]


@dataclass(frozen=True, slots=True)
class GeneratedTestRecord:
    """Persisted generated test suite for one source function and framework."""

    id: UUID
    repository_version_id: UUID
    function: RepositoryFunction
    end_line: int
    framework: UnitTestFramework
    test_file_path: str
    model: str
    summary: str
    test_code: str
    coverage: tuple[TestCoverageKind, ...]
    notes: tuple[str, ...]
    created_at: datetime
    updated_at: datetime
